name: kraken
channels:
  - conda-forge
  - defaults
  - mittagessen
dependencies:
  - python==3.6.6
  - lxml
  - future
  - regex
  - requests
  - click>=7.0
  - numpy
  - pillow
  - scipy
  - protobuf>=3.0.0
  - jinja2
  - torchvision
  - pytorch>=1.0.0
  - jsonschema
  - kraken
  - coremltools
